### ISSUE TITLE
bspump.common.BytesToStringParser

### ISSUE THREAD

**Issue by PremyslCerny** [Plesoun/bspump_kafka#3]
https://github.com/Plesoun/bspump_kafka/blob/feature-init/bspump_kafka_app/pipeline.py

bspump.common.BytesToStringParser převede byty na string, tj. ne na dictionary ... zkus nahradit bspump.common.BytesToStringParser za bspump.common.JsonBytesToDictParser ... tím pádem pak Transformator a další procesory dostanou `event` jako dictionary

**Comment by Plesoun** [comment]
To jsem zkousel a hodi to error:
BitSwan BSPump version 19.10
1 pipeline(s) ready.
Pipeline processing error in the 'KafkaPipeline' on depth 0
Traceback (most recent call last):
  File "C:\Users\jakub\OneDrive\Documents\TeskaLabs\bspump_kafka\venv\lib\site-packages\bspump\pipeline.py", line 268, in _do_process
    event = processor.process(context, event)
  File "C:\Users\jakub\OneDrive\Documents\TeskaLabs\bspump_kafka\venv\lib\site-packages\bspump\common\jsonbytes.py", line 39, in process
    return json.loads(json_result)
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\jakub\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Pipeline 'KafkaPipeline' stopped due to a processing error: Expecting value: line 1 column 1 (char 0) (<class 'json.decoder.JSONDecodeError'>)
Error on a pipeline is already set!
Pipeline 'KafkaPipeline' stopped due to a processing error: Expecting value: line 1 column 1 (char 0) (<class 'json.decoder.JSONDecodeError'>)
Exception in the source 'KafkaSource'
Traceback (most recent call last):

Kazdopadne chapu, ze BytesToStringParser z toho udela string, muj dotaz byl, jestli muzu nejak pracovat s tim stringem, nebo to jde jen s dictionary.

**Comment by PremyslCerny** [comment]
Záleží na tom, co za vstup očekávají ostatní procesory, které následují. Například MappingItemsProcessor očekává na vstupu dictionary, takže nic jiného mu tam dát nemůžeš. KafkaSink může dostat jak string, tak dictionary nebo bytes. Většina našich procesorů ale očekává dictionary.

Ta chyba vypadá, že v Kafkce nemáš validní JSONy, třeba {"aaa": "aaa", "aaa":["bbb"]} ale jen nějaké stringy, které nemůže převést na dictionary.

**Comment by Plesoun** [comment]
Parada:) problem byl v tom, ze mam na kafku nejake GUI a tam je "key" coz je asi index ci co, kazdopadne KafkaSource bere jen samoty ten message, kdyz jsem jako message dal neo co se podoba jsonu tak to funguje. Experimentuju s tim jak se to da transformovat. Diky! :)
